server:
  port: 3000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/LCC_Spring
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql : true
  config:
    import:
      - "application_qa.yml"

